### ISSUE TITLE
Timetable does not trim whitespace from course-name input.

### ISSUE THREAD

**Issue by caitelatte** [bshlgrs/bshlgrs.github.io#2]
When a user on a smart phone enters a course code and allows their keyboard to autocomplete it for them, they will usually have a space after the course code. Currently the timetable.js file doesn't accept this. Can be fixed with a .trim() call.

**Comment by bshlgrs** [comment]
Make a pull request; I'll merge it.

**Comment by caitelatte** [comment]
pull request is done, was just looking up how to tag :)

**Comment by caitelatte** [comment]
Pull request #3 is the matching one! :D
